#ifdef __cplusplus
extern "C" {
#endif

// declare Ruby registration method generated by SWIG in iap_wrap.c
extern void Init_Iap(void);

// this method executed once on start of program
void Init_Iap_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_Iap();

	// You can add some code to this place:


}

#ifdef __cplusplus
} //extern "C"
#endif